apis:
  - type: VK
    tokens:
      - fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    descriptor: ayzek
    groupId: 188280200
  - type: DS
    token: NNNNNNNNNNNNNNNNNNNNNNNN.NNNNNN.NNNNNNNNNNNNNNNNNNNNNNNNNNN
    descriptor: ayzek
  - type: TG
    token: 999999999:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    # For use in /command@mention syntax
    username: ayzek_bot
    descriptor: ayzek
