apis:
  - type: VK
    tokens:
      - fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    descriptor: ayzek
    groupId: 188280200
  - type: DS
    token: NNNNNNNNNNNNNNNNNNNNNNNN.NNNNNN.NNNNNNNNNNNNNNNNNNNNNNNNNNN
    descriptor: ayzek
